#!/usr/bin/env python3
"""
PDFium WASM build script.

This script builds PDFium as WebAssembly modules with two variants:
- pdfium-full.wasm: With Noto CJK fonts embedded
- pdfium-lite.wasm: Without fonts (FS API enabled for runtime font loading)

Both variants export the FS module for font management.

Usage:
    python3 build.py [--skip-fetch] [--skip-build] [--output-dir DIR] [--variant full|lite|both]
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

from config import (
    PDFIUM_VERSION,
    EXPORTED_FUNCTIONS,
    EXPORTED_RUNTIME_METHODS,
    get_build_config,
)


def run_command(cmd, cwd=None, env=None):
    """Run a command and print output."""
    print(f"Running: {' '.join(cmd)}")
    merged_env = os.environ.copy()
    if env:
        merged_env.update(env)
    result = subprocess.run(
        cmd, cwd=cwd, env=merged_env, capture_output=False, text=True
    )
    if result.returncode != 0:
        print(f"Command failed with return code {result.returncode}")
        sys.exit(1)
    return result


def fetch_pdfium(build_dir: Path):
    """Fetch PDFium source code using depot_tools."""
    pdfium_dir = build_dir / "pdfium"

    if pdfium_dir.exists():
        print(f"PDFium directory already exists: {pdfium_dir}")
        return pdfium_dir

    print("Fetching PDFium source...")

    # Create .gclient file
    gclient_content = f"""
solutions = [
  {{
    "name": "pdfium",
    "url": "https://pdfium.googlesource.com/pdfium.git@{PDFIUM_VERSION}",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {{}},
  }},
]
target_os = []
"""
    gclient_file = build_dir / ".gclient"
    gclient_file.write_text(gclient_content)

    # Sync PDFium
    run_command(["gclient", "sync", "--no-history"], cwd=build_dir)

    return pdfium_dir


def configure_pdfium(pdfium_dir: Path, out_dir: Path):
    """Configure PDFium build for WASM."""
    print("Configuring PDFium build...")

    # Create args.gn
    args_content = """
is_debug = false
pdf_is_standalone = true
pdf_enable_xfa = false
pdf_enable_v8 = false
is_component_build = false
clang_use_chrome_plugins = false
use_custom_libcxx = false
pdf_use_skia = false
pdf_bundle_freetype = true
is_clang = true
target_os = "wasm"
target_cpu = "wasm"
"""

    args_file = out_dir / "args.gn"
    args_file.parent.mkdir(parents=True, exist_ok=True)
    args_file.write_text(args_content)

    # Run gn gen
    run_command(["gn", "gen", str(out_dir)], cwd=pdfium_dir)


def build_pdfium(pdfium_dir: Path, out_dir: Path):
    """Build PDFium static library."""
    print("Building PDFium...")
    run_command(["ninja", "-C", str(out_dir), "pdfium"], cwd=pdfium_dir)


def link_wasm(pdfium_dir: Path, out_dir: Path, output_dir: Path, variant: str):
    """Link PDFium into WASM module using Emscripten."""
    print(f"Linking WASM module ({variant})...")

    output_dir.mkdir(parents=True, exist_ok=True)

    # Get build configuration for this variant
    build_config = get_build_config(variant)

    # Build exported functions flag
    exported_funcs = ",".join([f'"{f}"' for f in EXPORTED_FUNCTIONS])
    exported_runtime = ",".join([f'"{m}"' for m in EXPORTED_RUNTIME_METHODS])

    # Emscripten link command
    cmd = [
        "em++",
        "-s", f"EXPORTED_FUNCTIONS=[{exported_funcs}]",
        "-s", f"EXPORTED_RUNTIME_METHODS=[{exported_runtime}]",
    ]
    cmd.extend(build_config["flags"])

    # Add PDFium library
    cmd.append(str(out_dir / "obj" / "libpdfium.a"))

    # Include paths
    cmd.extend([
        "-I", str(pdfium_dir),
        "-I", str(pdfium_dir / "public"),
    ])

    # Run in output directory
    original_cwd = os.getcwd()
    os.chdir(output_dir)
    try:
        run_command(cmd)
    finally:
        os.chdir(original_cwd)

    print(f"WASM module created: {output_dir}/{build_config['output_name']}.wasm")


def create_types(output_dir: Path):
    """Create TypeScript type definitions."""
    print("Creating TypeScript types...")

    types_content = '''/**
 * PDFium WASM module types.
 * Auto-generated by build.py
 */

export interface EmscriptenFS {
  mkdir(path: string): void;
  writeFile(path: string, data: Uint8Array | string): void;
  readFile(path: string, opts?: { encoding?: string }): Uint8Array | string;
  unlink(path: string): void;
  rmdir(path: string): void;
  readdir(path: string): string[];
  stat(path: string): { mode: number };
  isDir(mode: number): boolean;
  isFile(mode: number): boolean;
}

export interface PDFiumModule {
  // Memory access
  HEAPU8: Uint8Array;
  HEAP32: Int32Array;

  // Virtual filesystem (for font loading)
  FS: EmscriptenFS;

  // WASM exports for memory management
  wasmExports: {
    malloc(size: number): number;
    free(ptr: number): void;
  };

  // Library initialization
  _PDFium_Init(): void;
  _FPDF_InitLibrary(): void;
  _FPDF_InitLibraryWithConfig(config: number): void;
  _FPDF_DestroyLibrary(): void;

  // Document handling
  _FPDF_LoadMemDocument(data: number, size: number, password: number): number;
  _FPDF_CloseDocument(document: number): void;
  _FPDF_GetLastError(): number;
  _FPDF_GetPageCount(document: number): number;

  // Page handling
  _FPDF_LoadPage(document: number, pageIndex: number): number;
  _FPDF_ClosePage(page: number): void;
  _FPDF_GetPageWidth(page: number): number;
  _FPDF_GetPageHeight(page: number): number;

  // Bitmap handling
  _FPDFBitmap_CreateEx(
    width: number,
    height: number,
    format: number,
    buffer: number,
    stride: number
  ): number;
  _FPDFBitmap_FillRect(
    bitmap: number,
    left: number,
    top: number,
    width: number,
    height: number,
    color: number
  ): void;
  _FPDF_RenderPageBitmap(
    bitmap: number,
    page: number,
    startX: number,
    startY: number,
    sizeX: number,
    sizeY: number,
    rotate: number,
    flags: number
  ): void;
  _FPDFBitmap_Destroy(bitmap: number): void;
  _FPDFBitmap_GetBuffer(bitmap: number): number;

  // Text extraction
  _FPDFText_LoadPage(page: number): number;
  _FPDFText_ClosePage(textPage: number): void;
  _FPDFText_CountChars(textPage: number): number;
  _FPDFText_GetText(
    textPage: number,
    startIndex: number,
    count: number,
    buffer: number
  ): number;

  // Emscripten utilities
  ccall(
    ident: string,
    returnType: string | null,
    argTypes: string[],
    args: unknown[]
  ): unknown;
  cwrap(
    ident: string,
    returnType: string | null,
    argTypes: string[]
  ): (...args: unknown[]) => unknown;
  setValue(ptr: number, value: number, type: string): void;
  getValue(ptr: number, type: string): number;
  UTF8ToString(ptr: number): string;
  stringToUTF8(str: string, outPtr: number, maxBytes: number): void;
  lengthBytesUTF8(str: string): number;
}

export interface LoadPdfiumOptions {
  wasmBinary?: ArrayBuffer;
  locateFile?: (path: string) => string;
  instantiateWasm?: (
    imports: WebAssembly.Imports,
    successCallback: (module: WebAssembly.Instance) => void
  ) => WebAssembly.Exports;
}

/** Load PDFium Full variant (with embedded CJK fonts) */
export declare function loadPdfiumFull(
  options?: LoadPdfiumOptions
): Promise<PDFiumModule>;

/** Load PDFium Lite variant (without fonts, FS enabled) */
export declare function loadPdfiumLite(
  options?: LoadPdfiumOptions
): Promise<PDFiumModule>;
'''
    types_file = output_dir / "pdfium.d.ts"
    types_file.write_text(types_content)

    print(f"TypeScript types created: {types_file}")


def main():
    parser = argparse.ArgumentParser(description="Build PDFium WASM")
    parser.add_argument(
        "--skip-fetch", action="store_true", help="Skip fetching PDFium source"
    )
    parser.add_argument(
        "--skip-build", action="store_true", help="Skip building PDFium"
    )
    parser.add_argument(
        "--variant",
        choices=["full", "lite", "both"],
        default="both",
        help="Which variant to build (default: both)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("/output"),
        help="Output directory for WASM files",
    )
    parser.add_argument(
        "--build-dir",
        type=Path,
        default=Path("/build"),
        help="Build directory",
    )
    args = parser.parse_args()

    build_dir = args.build_dir
    output_dir = args.output_dir
    pdfium_dir = build_dir / "pdfium"
    out_dir = pdfium_dir / "out" / "wasm"

    # Fetch PDFium
    if not args.skip_fetch:
        fetch_pdfium(build_dir)

    # Configure and build
    if not args.skip_build:
        configure_pdfium(pdfium_dir, out_dir)
        build_pdfium(pdfium_dir, out_dir)

    # Determine which variants to build
    variants = ["full", "lite"] if args.variant == "both" else [args.variant]

    # Link WASM for each variant
    for variant in variants:
        link_wasm(pdfium_dir, out_dir, output_dir, variant)

    # Create TypeScript types
    create_types(output_dir)

    print("\nBuild complete!")
    print(f"Output files in {output_dir}:")
    for f in sorted(output_dir.iterdir()):
        size = f.stat().st_size
        size_str = f"{size / 1024 / 1024:.2f} MB" if size > 1024 * 1024 else f"{size / 1024:.2f} KB"
        print(f"  {f.name}: {size_str}")


if __name__ == "__main__":
    main()
