import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    latin: 'src/fonts/latin.ts',
    japanese: 'src/fonts/japanese.ts',
    korean: 'src/fonts/korean.ts',
    'chinese-simplified': 'src/fonts/chinese-simplified.ts',
    'chinese-traditional': 'src/fonts/chinese-traditional.ts',
    arabic: 'src/fonts/arabic.ts',
    hebrew: 'src/fonts/hebrew.ts',
    devanagari: 'src/fonts/devanagari.ts',
    bengali: 'src/fonts/bengali.ts',
    tamil: 'src/fonts/tamil.ts',
    telugu: 'src/fonts/telugu.ts',
    gujarati: 'src/fonts/gujarati.ts',
    kannada: 'src/fonts/kannada.ts',
    malayalam: 'src/fonts/malayalam.ts',
    oriya: 'src/fonts/oriya.ts',
    gurmukhi: 'src/fonts/gurmukhi.ts',
    sinhala: 'src/fonts/sinhala.ts',
    thai: 'src/fonts/thai.ts',
    lao: 'src/fonts/lao.ts',
    myanmar: 'src/fonts/myanmar.ts',
    khmer: 'src/fonts/khmer.ts',
    armenian: 'src/fonts/armenian.ts',
    georgian: 'src/fonts/georgian.ts',
    ethiopic: 'src/fonts/ethiopic.ts',
    all: 'src/all.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  outDir: 'dist',
  shims: true,
  external: ['@noto-pdf-ts/core', 'node:fs/promises', 'node:path', 'node:url'],
});
