/**
 * Type definitions for PDFium Lite WASM module.
 *
 * This module is generated by Emscripten without embedded fonts.
 * Use registerFonts() to add fonts at runtime.
 */

import type { LoadPdfiumOptions, PDFiumModule } from '../types.js';

/**
 * Loads the PDFium Lite WASM module.
 *
 * @param options - Optional configuration for loading the module
 * @returns Promise resolving to the initialized PDFium module
 */
declare function loadPdfiumLite(options?: LoadPdfiumOptions): Promise<PDFiumModule>;

export default loadPdfiumLite;
export { loadPdfiumLite };
