/**
 * Type definitions for PDFium Full WASM module.
 *
 * This module is generated by Emscripten and includes embedded CJK fonts.
 */

import type { LoadPdfiumOptions, PDFiumModule } from '../types.js';

/**
 * Loads the PDFium Full WASM module.
 *
 * @param options - Optional configuration for loading the module
 * @returns Promise resolving to the initialized PDFium module
 */
declare function loadPdfiumFull(options?: LoadPdfiumOptions): Promise<PDFiumModule>;

export default loadPdfiumFull;
export { loadPdfiumFull };
